#!/bin/bash

#$   -q development
#$   -V
#$   -cwd
#$   -pe 1way 16
#$   -l h_rt=0:05:00

#$   -j y
#$   -N papirun_wait
#$   -o $JOB_NAME.oe$JOB_ID
#$   -e $JOB_NAME.oe$JOB_ID
##$   -M eijkhout@tacc.utexas.edu
##$   -m e

#$ -A A-ccsc

sleep 300

